# Download a prebuilt Ruby version, install dependencies, and run the default Rake task

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        ruby: ['2.6', '2.7', 'head']
        operating-system: [ubuntu-latest]
        include:
          - ruby: 2.7
            operating-system: windows-latest

    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run rake
        run: bundle exec rake
